# Generated by Django 2.0.1 on 2018-01-08 13:21

import coupon.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('batch', models.PositiveIntegerField(default=0)),
                ('sn', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('pwd', models.CharField(default=coupon.models.Ticket.generate_pwd, max_length=8)),
                ('product', models.PositiveSmallIntegerField(choices=[(1, '玖玖红颜礼盒装900g'), (2, '玖玖红颜礼盒装1800g'), (3, '玖玖红颜普通装1300g')], default=1)),
                ('actived', models.BooleanField(default=False)),
                ('date_creat', models.DateField(auto_now_add=True)),
                ('date_effective', models.DateField(default=datetime.date.today)),
                ('date_expire', models.DateField()),
                ('date_use', models.DateTimeField(blank=True)),
                ('order_name', models.CharField(blank=True, max_length=16)),
                ('order_phone', models.CharField(blank=True, max_length=11)),
                ('order_address', models.TextField(blank=True)),
                ('order_comments', models.CharField(blank=True, max_length=20)),
                ('order_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
